# Generated by Django 4.2.29 on 2026-03-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_status_order_is_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_order_id',
            new_name='stripe_payment_intent',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_payment_id',
            new_name='stripe_session_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
